imports:
    - { resource: parameters.yml }
    - { resource: '@OpiferCmsBundle/Resources/config/security.yml' }
    - { resource: services.yml }
    - { resource: '@OpiferCmsBundle/Resources/config/config.yml' }
